apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test
  labels:
    app: python-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-test
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
      - name: python-test
        image: ngocvinhvu/argocd-test:9bda856a340e2fe3575d557bab4ac1a593fbd74e
        ports:
        - containerPort: 5000